name: 'Setup Terraform docs'
description: 'Install and setup Terraform docs executable'
author: 'Labyrinth Labs'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  terraform_docs_version:
    description: Terraform docs version to install
    required: true
branding:
  icon: play-circle
  color: blue
